[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools_scm",
    "attrs",
    "httpx",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "cvrf2csaf/_version.py"