# TODO: use version derived from git revision
cvrf2csaf_version: 1.0
cvrf2csaf_name: CVRF-CSAF-Converter

# General config
# Force conversion, produces invalid output to be fixed manually
force: false

# Document leaf elements
csaf_version: 2.0

# Document Publisher
publisher_name: Publisher Name
publisher_namespace: Publisher Namespace

# Document Tracking
force_update_revision_history: false

# Document References
force_insert_default_reference_category: true

# Vulnerability
remove_CVSS_values_without_vector: false

default_CVSS3_version : "3.0"